name: Build

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            pio_lib_path: D:\a\Luos
          - os: macos-latest
            pio_lib_path: ~/work/Luos
          - os: ubuntu-latest
            pio_lib_path: ~/work/Luos

    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          npm install -g clang-format@1.5.0

      - name: Check out getting started repository
        uses: actions/checkout@v2

      - name: Check for code format
        if: ${{ runner.os != 'Windows' }}
        run: python .github/workflows/run-clang-format.py -r .

      - name: Run PlatformIO
        run: |
          for d in ./*/
          do
            # Parse all folder
            if [ -f "$d/platformio.ini" ]
            then
              # This is a PIO project compile it
              echo "Compiling : $d"
              platformio run -d $d
            fi
          done